minSdk = 24
targetSdk = 34
versionCode = 1
versionName = "1.0"
signingConfig {
    defaultConfig {
        keyAlias 'debugKey'
        keyPassword 'android'
        storeFile file('../../../debug.keystore')
        storePassword 'android'
    }
}
